apiVersion: v1
kind: Service
metadata:
  name: php-apache
spec:
  clusterIP: 172.24.253.251
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: php-apache
  type: ClusterIP

