# This mounts the nfs volume claim into /mnt and continuously
# overwrites /mnt/index.html with the time and hostname of the pod.

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nfs-busybox
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: nfs-busybox
    spec:
      containers:
      - image: rmt.example.com:5000/busybox
        command:
          - sh
          - -c
          - 'while true; do date > /mnt/index.html; hostname >> /mnt/index.html; sleep $(($RANDOM % 5 + 5)); done'
        imagePullPolicy: IfNotPresent
        name: busybox
        volumeMounts:
          # name must match the volume name below
          - name: nfs-vol-01
            mountPath: "/mnt"
      volumes:
      - name: nfs-vol-01
        persistentVolumeClaim:
          claimName: nfs-vol-01
