# This pod mounts the nfs volume claim into /usr/share/nginx/html and
# serves a simple web page.

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nfs-web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: web-frontend
    spec:
      containers:
      - name: web
        image: rmt.example.com:5000/nginx:1.9.0
        ports:
          - name: web
            containerPort: 80
        volumeMounts:
            - name: nfs-vol-01
              mountPath: "/usr/share/nginx/html"
      volumes:
      - name: nfs-vol-01
        persistentVolumeClaim:
          claimName: nfs-vol-01
