---
# Define the Role's permissions in Kubernetes
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: manage-namespace-1
  namespace: namespace-1
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
# Map a LDAP group to this Kubernetes role
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: manage-namspace-1-binding
  namespace: namespace-1
subjects:
- kind: Group
  name: group1
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: manage-namespace-1
  apiGroup: rbac.authorization.k8s.io
