apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: heimdall-shared-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: heimdall-shared
    spec:
      containers:
        - name: heimdall-pod
          image: linuxserver/heimdall
          volumeMounts:
            - name: heimdall-pvc-shared
              mountPath: "/config"
      volumes:
        - name: heimdall-pvc-shared
          persistentVolumeClaim:
            claimName: heimdall-shared-claim
