apiVersion: v1
kind: Pod
metadata:
  name: envar-demo
  labels:
    purpose: demonstrate-envars
spec:
  containers:
  - name: envar-demo-container
    image: rmt.example.com:5000/gcr.io/google-samples/node-hello:1.0
    env:
    - name: DEMO_GREETING
      value: "SUSE Rocks!"
